In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy.integrate import odeint

# Equação Numérica

Como $\frac{dT_i}{dt} \approx \frac{T_i^{l+1}-T_i^{l}}{\Delta t}$, temos que:

$\frac{dT_i}{dt} = \alpha \frac{T_{i+1} - 2T_i + T_{i-1}}{\Delta x^2} \approx \frac{T_i^{l+1}-T_i^{l}}{\Delta t} = \alpha \frac{T_{i+1} - 2T_i + T_{i-1}}{\Delta x^2}$

$\Rightarrow T_i^{l+1} = T_i^{l} + λ(T_{i+1} - 2T_i + T_{i-1})$, onde $\lambda = \alpha \frac{\Delta t}{\Delta x^2}$


Como $n = 6$, temos que a separação se dá por uma matriz $M_{6 \times 6}$. Considerando como no artigo um valor $\Delta x = 5 cm$ e $\Delta t = 5s$, temos que $\lambda = 0,2$ e a equação resultante é

\begin{equation}
T^{l}_{i} = -0.2T^{l+1}_{i-1} + 1.4T^{l+1}_{i} - 0.2T^{l+1}_{i+1}
\end{equation}

In [7]:
A=np.array([[1.4,-0.2,0,0,0],[-0.2,1.4,-0.2,0,0],[0,-0.2,1.4,-0.2,0],[0,0,-0.2,1.4,-0.2],[0,0,0,-0.2,1.4]])
b=np.array([50,50,50,50,50])
matrix = []

for i in range(20):
  u=np.linalg.solve(A, b).tolist()
  b = np.array(u)
  matrix.append(u)

list_as_array = np.array(matrix)

print(list_as_array)

[[42.70186335 48.91304348 49.68944099 48.91304348 42.70186335]
 [37.25261371 47.25897921 48.99502334 47.25897921 37.25261371]
 [33.08510438 45.33266212 47.94863442 45.33266212 33.08510438]
 [29.81796856 43.300258   46.62052687 43.300258   29.81796856]
 [27.19203191 41.25438059 45.08734222 41.25438059 27.19203191]
 [25.02940227 39.24565634 43.41828911 39.24565634 25.02940227]
 [23.20682904 37.30079193 41.67043277 37.30079193 23.20682904]
 [21.63815126 35.43291362 39.88828444 35.43291362 21.63815126]
 [20.26260542 33.64748164 38.10519793 33.64748164 20.26260542]
 [19.0369569  31.94567117 36.34533314 31.94567117 19.0369569 ]
 [17.93015536 30.32630307 34.62561026 30.32630307 17.93015536]
 [16.91967444 28.78694425 32.95741997 28.78694425 16.91967444]
 [15.98898647 27.32453306 31.34802371 27.32453306 15.98898647]
 [15.1258093  25.93573278 29.80165488 25.93573278 15.1258093 ]
 [14.32088232 24.61712975 28.32036198 24.61712975 14.32088232]
 [13.56710775 23.36534267 26.90464218 23.36534267 13.56